//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonClass", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Hospital_Management_System.LoginService.PatientClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Hospital_Management_System.LoginService.DoctorClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Hospital_Management_System.LoginService.Nurseclass))]
    public partial class PersonClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelnumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dob {
            get {
                return this.DobField;
            }
            set {
                if ((object.ReferenceEquals(this.DobField, value) != true)) {
                    this.DobField = value;
                    this.RaisePropertyChanged("Dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobnum {
            get {
                return this.MobnumField;
            }
            set {
                if ((object.ReferenceEquals(this.MobnumField, value) != true)) {
                    this.MobnumField = value;
                    this.RaisePropertyChanged("Mobnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nic {
            get {
                return this.NicField;
            }
            set {
                if ((object.ReferenceEquals(this.NicField, value) != true)) {
                    this.NicField = value;
                    this.RaisePropertyChanged("Nic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telnum {
            get {
                return this.TelnumField;
            }
            set {
                if ((object.ReferenceEquals(this.TelnumField, value) != true)) {
                    this.TelnumField = value;
                    this.RaisePropertyChanged("Telnum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientClass", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    [System.SerializableAttribute()]
    public partial class PatientClass : Hospital_Management_System.LoginService.PersonClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BgroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateAdmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDischField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bgroup {
            get {
                return this.BgroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BgroupField, value) != true)) {
                    this.BgroupField = value;
                    this.RaisePropertyChanged("Bgroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country1 {
            get {
                return this.Country1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Country1Field, value) != true)) {
                    this.Country1Field = value;
                    this.RaisePropertyChanged("Country1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateAdmit {
            get {
                return this.DateAdmitField;
            }
            set {
                if ((object.ReferenceEquals(this.DateAdmitField, value) != true)) {
                    this.DateAdmitField = value;
                    this.RaisePropertyChanged("DateAdmit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDisch {
            get {
                return this.DateDischField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDischField, value) != true)) {
                    this.DateDischField = value;
                    this.RaisePropertyChanged("DateDisch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maritial {
            get {
                return this.MaritialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritialField, value) != true)) {
                    this.MaritialField = value;
                    this.RaisePropertyChanged("Maritial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatID {
            get {
                return this.PatIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PatIDField, value) != true)) {
                    this.PatIDField = value;
                    this.RaisePropertyChanged("PatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorClass", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    [System.SerializableAttribute()]
    public partial class DoctorClass : Hospital_Management_System.LoginService.PersonClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChnlfeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Chnlfee {
            get {
                return this.ChnlfeeField;
            }
            set {
                if ((this.ChnlfeeField.Equals(value) != true)) {
                    this.ChnlfeeField = value;
                    this.RaisePropertyChanged("Chnlfee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocId {
            get {
                return this.DocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdField, value) != true)) {
                    this.DocIdField = value;
                    this.RaisePropertyChanged("DocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualif {
            get {
                return this.QualifField;
            }
            set {
                if ((object.ReferenceEquals(this.QualifField, value) != true)) {
                    this.QualifField = value;
                    this.RaisePropertyChanged("Qualif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speclty {
            get {
                return this.SpecltyField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecltyField, value) != true)) {
                    this.SpecltyField = value;
                    this.RaisePropertyChanged("Speclty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nurseclass", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    [System.SerializableAttribute()]
    public partial class Nurseclass : Hospital_Management_System.LoginService.PersonClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NurseId1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiftField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NurseId1 {
            get {
                return this.NurseId1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NurseId1Field, value) != true)) {
                    this.NurseId1Field = value;
                    this.RaisePropertyChanged("NurseId1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualif {
            get {
                return this.QualifField;
            }
            set {
                if ((object.ReferenceEquals(this.QualifField, value) != true)) {
                    this.QualifField = value;
                    this.RaisePropertyChanged("Qualif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryField, value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shift {
            get {
                return this.ShiftField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiftField, value) != true)) {
                    this.ShiftField = value;
                    this.RaisePropertyChanged("Shift");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillClass", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    [System.SerializableAttribute()]
    public partial class BillClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillTotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DaysAdmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DaysDischField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillTot {
            get {
                return this.BillTotField;
            }
            set {
                if ((this.BillTotField.Equals(value) != true)) {
                    this.BillTotField = value;
                    this.RaisePropertyChanged("BillTot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((this.ChannelField.Equals(value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Charge {
            get {
                return this.ChargeField;
            }
            set {
                if ((this.ChargeField.Equals(value) != true)) {
                    this.ChargeField = value;
                    this.RaisePropertyChanged("Charge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DaysAdmit {
            get {
                return this.DaysAdmitField;
            }
            set {
                if ((this.DaysAdmitField.Equals(value) != true)) {
                    this.DaysAdmitField = value;
                    this.RaisePropertyChanged("DaysAdmit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DaysDisch {
            get {
                return this.DaysDischField;
            }
            set {
                if ((this.DaysDischField.Equals(value) != true)) {
                    this.DaysDischField = value;
                    this.RaisePropertyChanged("DaysDisch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatID {
            get {
                return this.PatIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PatIDField, value) != true)) {
                    this.PatIDField = value;
                    this.RaisePropertyChanged("PatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ward {
            get {
                return this.WardField;
            }
            set {
                if ((object.ReferenceEquals(this.WardField, value) != true)) {
                    this.WardField = value;
                    this.RaisePropertyChanged("Ward");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.INurseService")]
    public interface INurseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INurseService/AddNurse", ReplyAction="http://tempuri.org/INurseService/AddNurseResponse")]
        void AddNurse(Hospital_Management_System.LoginService.Nurseclass nurse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INurseService/getNurse", ReplyAction="http://tempuri.org/INurseService/getNurseResponse")]
        System.Data.DataTable getNurse(string fname, string lname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INurseServiceChannel : Hospital_Management_System.LoginService.INurseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NurseServiceClient : System.ServiceModel.ClientBase<Hospital_Management_System.LoginService.INurseService>, Hospital_Management_System.LoginService.INurseService {
        
        public NurseServiceClient() {
        }
        
        public NurseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NurseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NurseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NurseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNurse(Hospital_Management_System.LoginService.Nurseclass nurse) {
            base.Channel.AddNurse(nurse);
        }
        
        public System.Data.DataTable getNurse(string fname, string lname) {
            return base.Channel.getNurse(fname, lname);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.IBillService")]
    public interface IBillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/AddBill", ReplyAction="http://tempuri.org/IBillService/AddBillResponse")]
        void AddBill(Hospital_Management_System.LoginService.BillClass bill);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillServiceChannel : Hospital_Management_System.LoginService.IBillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceClient : System.ServiceModel.ClientBase<Hospital_Management_System.LoginService.IBillService>, Hospital_Management_System.LoginService.IBillService {
        
        public BillServiceClient() {
        }
        
        public BillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBill(Hospital_Management_System.LoginService.BillClass bill) {
            base.Channel.AddBill(bill);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.IPatientService")]
    public interface IPatientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/AddPatient", ReplyAction="http://tempuri.org/IPatientService/AddPatientResponse")]
        void AddPatient(Hospital_Management_System.LoginService.PatientClass patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/getPatient", ReplyAction="http://tempuri.org/IPatientService/getPatientResponse")]
        System.Data.DataTable getPatient(string fname, string lname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPatientServiceChannel : Hospital_Management_System.LoginService.IPatientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientServiceClient : System.ServiceModel.ClientBase<Hospital_Management_System.LoginService.IPatientService>, Hospital_Management_System.LoginService.IPatientService {
        
        public PatientServiceClient() {
        }
        
        public PatientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPatient(Hospital_Management_System.LoginService.PatientClass patient) {
            base.Channel.AddPatient(patient);
        }
        
        public System.Data.DataTable getPatient(string fname, string lname) {
            return base.Channel.getPatient(fname, lname);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.IDoctorService")]
    public interface IDoctorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/AddDoctor", ReplyAction="http://tempuri.org/IDoctorService/AddDoctorResponse")]
        void AddDoctor(Hospital_Management_System.LoginService.DoctorClass doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/getDoctor", ReplyAction="http://tempuri.org/IDoctorService/getDoctorResponse")]
        System.Data.DataTable getDoctor(string fname, string lname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/getDoctorPriceDetails", ReplyAction="http://tempuri.org/IDoctorService/getDoctorPriceDetailsResponse")]
        Hospital_Management_System.LoginService.DoctorClass getDoctorPriceDetails();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoctorServiceChannel : Hospital_Management_System.LoginService.IDoctorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoctorServiceClient : System.ServiceModel.ClientBase<Hospital_Management_System.LoginService.IDoctorService>, Hospital_Management_System.LoginService.IDoctorService {
        
        public DoctorServiceClient() {
        }
        
        public DoctorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddDoctor(Hospital_Management_System.LoginService.DoctorClass doctor) {
            base.Channel.AddDoctor(doctor);
        }
        
        public System.Data.DataTable getDoctor(string fname, string lname) {
            return base.Channel.getDoctor(fname, lname);
        }
        
        public Hospital_Management_System.LoginService.DoctorClass getDoctorPriceDetails() {
            return base.Channel.getDoctorPriceDetails();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/login", ReplyAction="http://tempuri.org/ILoginService/loginResponse")]
        bool login(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : Hospital_Management_System.LoginService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Hospital_Management_System.LoginService.ILoginService>, Hospital_Management_System.LoginService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string username, string password) {
            return base.Channel.login(username, password);
        }
    }
}
